fix: add branch and sha to catalog entries
projectatomic/ai-studio pull request #174
Opened 2024-01-29 16:49 UTC by lstocchi

This PR adds the branch and commit sha properties so that we can checkout the specific branch/commit.

it resolves #142

2024-01-29 17:00 UTC, jeffmaury requested changes
Also the ref field should be optional

2024-01-29 17:10 UTC, lstocchi commented on packages/backend/src/ai.json
> +      "branch": "main",
By reading the definition it says "A valid ref can be a SHA1 tag or a branch name", so I think they just do a simple clone. I don't see how i can checkout if i want to take branch 'prod' until commit 'blabla'.

2024-01-30 09:41 UTC, lstocchi commented on packages/backend/src/ai.json
> +      "branch": "main",
i was sure you needed to clone using the branch. Fixed 👍

2024-01-30 09:43 UTC, lstocchi commented
I forgot to make the ref optional. Updating

2024-01-30 09:45 UTC, feloy commented on packages/shared/src/models/IRecipe.ts
> +  ref: string;
I think this should be optional. You could add some test to assert it works with an undefined ref

2024-01-30 10:35 UTC, jeffmaury reviewed
Make ref optional otherwise I'm good

2024-01-30 11:01 UTC, feloy approved these changes

2024-01-30 11:09 UTC, jeffmaury approved these changes
LGTM

2024-01-30 11:25 UTC, merged