fix: dropping popularity property and column
projectatomic/ai-studio pull request #360
Opened 2024-02-16 16:15 UTC by axel7083

### What does this PR do?

Remove the popularity column from ModelInfo interface

### Screenshot / video of UI

### What issues does this PR fix or reference?

Fixes https://github.com/projectatomic/ai-studio/issues/278

### How to test this PR?

2024-02-16 17:26 UTC, jeffmaury requested changes
Catalog should be updated as well

2024-02-19 10:09 UTC, feloy approved these changes

2024-02-19 11:01 UTC, axel7083 commented
cc @jeffmaury

2024-02-19 11:03 UTC, jeffmaury approved these changes
LGTM

2024-02-19 11:03 UTC, merged