feat(inference): adding delete button
projectatomic/ai-studio pull request #548
Opened 2024-03-14 13:56 UTC by axel7083

### What does this PR do?

This PR is adding the logic to delete an InferenceServer. 

> To enhance the UI we will need https://github.com/projectatomic/ai-studio/issues/547 to store the _transition_ states

### Screenshot / video of UI

https://github.com/projectatomic/ai-studio/assets/42176370/c0de3387-cde9-4beb-bbac-d2f1e0dfe646

### What issues does this PR fix or reference?

Fixes https://github.com/projectatomic/ai-studio/issues/546

### How to test this PR?

- [x] unit tests has been provided

2024-03-15 13:54 UTC, jeffmaury requested changes
Missing confirmation dialog

2024-03-15 14:13 UTC, axel7083 commented
> Missing confirmation dialog

@jeffmaury good remarks I rebased and added a confirmation dialog as visible in the following video

https://github.com/projectatomic/ai-studio/assets/42176370/22e122a7-e641-4822-96c0-e8d64aa293df

2024-03-19 08:49 UTC, jeffmaury approved these changes
LGTM comment wise

2024-03-19 08:49 UTC, jeffmaury commented on packages/backend/src/managers/inference/inferenceManager.ts
> +  private removeInferenceServerRef(containerId: string): void {
Rename as removeInferenceServerReference

2024-03-19 08:59 UTC, axel7083 commented on packages/backend/src/managers/inference/inferenceManager.ts
> +  private removeInferenceServerRef(containerId: string): void {
✅  done

2024-03-19 09:05 UTC, merged